services:
    app:
        build: ./php
        volumes:
            - ./php/src:/var/www/html
        expose:
            - 9000
        restart: always
        depends_on:
            db:
                condition: service_healthy
        networks:
            - my-network

    web:
        build: ./nginx
        volumes:
            - ./php/src:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - app
            - db
        networks:
            - my-network

    db:
        build: ./psql

        volumes:
            - ./psql/pgdata:/var/lib/postgresql/data
            - ./psql/init.sql:/docker-entrypoint-initdb.d/init.sql # Only executed when the container is created with a empty data directory
        environment:
            POSTGRES_DB: app # Database name
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 1q2w3e4r
        ports:
            - 5432:5432
        restart: always
        networks:
            - my-network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U admin -d app'] # '-d' specifies the database name
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    my-network:
        driver: bridge
